### ISSUE TITLE
Export as PDF does not export the full Note

### ISSUE THREAD

**Issue by mrth3p1auge** [klaussinani/tusk#141]
**Describe the bug**
After selecting a Note, if you choose to export as PDF from the file drop down or <CTRL> <SHIFT> E, and save the file, you will find it did not export the note, but instead made a screen shot of it, only the viewable part of the note was exported, not the note in it's entirety. 

**To Reproduce**
Select a note that is multi-page ( extends past the current view window ), export as PDF by pressing <CNTRL><SHIFT> E, save the PDF file to your system.  Now open the saved PDF, you will find it only exported the "viewable" portion of the note. You can also go to the same note, scroll down to a mid section and repeat above, you will yet another "portion" of the note.

**Expected behavior**
When exporting a note, I would expect the entire note to export; as it does in the Evernote client, and in nixnote2.

**Technical Info (please complete the following information)**
 - OS: Linux 4.18.0  -- distro Debian 9.6
 - Tusk Version:0.13

**Additional context**
I do understand that this maybe a limitation of a API that is being used.

**Comment by mrth3p1auge** [comment]
This issue appears to have been resolved with version 0.15:  PDF export now pulls / exports the full note, not just the "displayed" portion.

**Comment by ksonbol** [comment]
This bug is back again using version 0.22.0 for Linux (using Ubuntu 16.04).

**Comment by SpeederX** [comment]
> This bug is back again using version 0.22.0 for Linux (using Ubuntu 16.04).

yea, i had the same problem, i'm downloading the 0.23 to check if it's just 0.22 related

**Comment by SpeederX** [comment]
Update: i just installed the new version : 0.23.0 64 bit
There's still this problem, but i tried to export after selecting all the text (CTRL+A) already in the note and the whole document was there! I suppose there should be 3 different modes at these point: print displayed, print whole document, print selected; as contextual functionalities of course, not separated buttons. The default should be print the whole document tho, not just "on screen" content of the note.
